DDP: True
seed: 0 #随机数种子
device: cuda:0 #模型使用单卡时的显卡名称
save_dir: saved #保存路径
num_epochs: 100 #训练的epoch数目
num_log_steps: 0 #每多少个step输出log, 0 means no output
num_valid_epochs: 1 #每多少个epoch运行valid
num_save_epochs: 5
save_model: True
scheduler_interval: step
batch_size: &batch_size 128

load_saved_model: False
random_data_split: False

task_names: ['XpressoRNA_HepG2', 'XpressoRNA_K562', 'GosaiMPRA_HepG2', 'GosaiMPRA_K562']
selected_train_datasets_idx: [0]
selected_valid_datasets_idx: [0]

1_dataset_basic_config: &1_dataset_basic_config
    bed_exp_path: '/home/hxcai/cell_type_specific_CRE/data/Xpresso/merged_bed_exp.csv'
    genome_path: '/home/hxcai/genome/hg38.fa'
    strand_specific: True
    select_seq_region: [3000, 13500]

2_dataset_basic_config: &2_dataset_basic_config
    seq_exp_path: '/home/hxcai/cell_type_specific_CRE/data/GosaiMPRA/GosaiMPRA_len_200_subset_diff>1.csv'
    input_column: 'seq'

train_dataset_filter_config: &train_dataset_filter_config
    filter_column: 'chr'
    filter_in_list: 
    filter_not_in_list: ['chr1', 'chrX', 'chrY', 'chrnan']

valid_dataset_filter_config: &valid_dataset_filter_config
    filter_column: 'chr'
    filter_in_list: ['chr1']
    filter_not_in_list: 

train_datasets:
    -   type: BedDataset
        args:
            <<: *1_dataset_basic_config
            <<: *train_dataset_filter_config
            output_column: 'HepG2'
            task_idx: [0, 0, 0]
            
    # -   type: BedDataset
    #     args:
    #         <<: *1_dataset_basic_config
    #         <<: *train_dataset_filter_config
    #         output_column: 'K562'
    #         task_idx: [1, 1, 0]
            
    # -   type: SeqLabelDataset
    #     args:
    #         <<: *2_dataset_basic_config
    #         <<: *train_dataset_filter_config
    #         output_column: 'HepG2'
    #         task_idx: [2, 0, 1]

    # -   type: SeqLabelDataset
    #     args:
    #         <<: *2_dataset_basic_config
    #         <<: *train_dataset_filter_config
    #         output_column: 'K562'
    #         task_idx: [3, 1, 1]


model:
    type: Xpresso
    args:
        input_length: 10500
        output_dim: 1

# model:
#     type: MyBasset
#     args:
#         input_length: 10500
#         output_dim: 1
#         conv_channels_list: [200,200,200,200,200,200,200,200,200,200,200,200,200,200,200]
#         conv_kernel_size_list: [3,3,3,3,3,3,3,3,3,3,3,3,3,3,3]
#         pool_kernel_size_list: [1,1,1,1,2,1,1,1,1,2,1,1,1,1,2]
#         linear_channels_list: [1000,100]
#         conv_dropout_rate: 0.1
#         linear_dropout_rate: 0.5


data_loader:
    type: DataLoader
    args:
        batch_size: *batch_size
        num_workers: 1
        pin_memory: True
        drop_last: False

optimizer:
    type: Adam
    args:
        lr: 3.0e-4
        weight_decay: 1.0e-4

lr_scheduler:
    type: CosineAnnealingWarmRestarts
    args: 
        T_0: 20

loss_func:
    type: MultiTaskLoss
    args:
        loss_list: ['MSELoss', 'MSELoss']

metric_func_list:
    - type: Pearson
    - type: Spearman

early_stopper:
    type: EarlyStopping
    args:
        patience: 5
        delta: 0
        target: min
        verbose: True

logger:
    version: 1
    disable_existing_loggers: false
    formatters:
        simple:
            format: '%(message)s'
        complex:
            format: '%(asctime)s - %(levelname)s - %(message)s'
    handlers:
        console_handler:
            class: logging.StreamHandler
            level: INFO
            formatter: complex
            stream: ext://sys.stdout
        info_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: complex
            filename: info.log
            maxBytes: 10485760
            backupCount: 10
            encoding: utf8
        debug_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: DEBUG
            formatter: complex
            filename: debug.log
            maxBytes: 10485760
            backupCount: 10
            encoding: utf8
    root:
        level: DEBUG
        handlers:
            - console_handler
            - info_file_handler
            - debug_file_handler
